version: "3"
services:
  mapcdb:
    container_name: mapcdb
    build:
      context: .
      dockerfile: Dockerfile-mariadb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - type: bind
        source: ../db/
        target: /var/lib/mysql
    environment:
      - "MYSQL_DATABASE=dbname"
      - "MYSQL_USER=userid"
      - "MYSQL_PASSWORD=userpass"
      - "MYSQL_ROOT_PASSWORD=root_password"
      - "TZ=Asia/Seoul"
  mapcweb:
    container_name: mapcweb
    build:
      context: .
      dockerfile: Dockerfile-php-apache
    volumes:
      - type: bind
        source: ../web/
        target: /var/www/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mapcdb
  mapcphpmyadmin:
    container_name: mapcphpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mapcdb
    ports:
      - 8185:80
    environment:
      PMA_HOST: mapcdb
      PMA_USER: root
      PMA_PASSWORD: root_password
      PMA_ARBITRARY: 1
