version: "3"
services:
  wooygdb:
    container_name: wooygdb
    build:
      context: .
      dockerfile: Dockerfile-mariadb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - type: bind
        source: ../db/
        target: /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - "MYSQL_DATABASE=dbname"
      - "MYSQL_USER=userid"
      - "MYSQL_PASSWORD=userpass"
      - "MYSQL_ROOT_PASSWORD=root_password"
      - "TZ=Asia/Seoul"
  wooygweb:
    container_name: wooygweb
    build:
      context: .
      dockerfile: Dockerfile-php-apache
    volumes:
      - type: bind
        source: ../web/
        target: /var/www/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wooygdb
  wooygphpmyadmin:
    container_name: wooygphpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - wooygdb
    ports:
      - 127.0.0.1:8185:80
    environment:
      PMA_HOST: wooygdb
      PMA_USER: root
      PMA_PASSWORD: root_password
      PMA_ARBITRARY: 1
